### PR TITLE
Bug Fix for Import

### LINKED ISSUE #170: Problem Importing Exported File
When exporting the preloaded data and the importing it back into the system, there is a problem in importing as it says that a tag name is invalid. If anything is exported, by right it should be in the correct format and appropriate to import. However, this does not seem to be the case. Refer to screenshot.
 

<hr><sub>[original: Abhiman2211/ped#12]<br/>
</sub>

### PR DESCRIPTION
**Pull request by jonathantjendana**
Fixes #170

### CODE REVIEW

File: src/main/java/seedu/moneygowhere/logic/commands/ImportCommand.java [hunk 1]
```diff
@@ -72,7 +78,12 @@ private static Spending createSpending(Map<String, String> map) throws ParseExce
         Date date = ParserUtil.parseDate(metaDate);
         Remark remark = ParserUtil.parseRemark(metaRemarks);
         Cost cost = ParserUtil.parseCost(metaCost);
-        Set<Tag> tagList = ParserUtil.parseTags(Arrays.asList(tags));
+        Set<Tag> tagList;
+        if (metaTags.equals("")) {
```
Comment (Nanosync) [inline src/main/java/seedu/moneygowhere/logic/commands/ImportCommand.java]: .isEmpty()

File: src/main/java/seedu/moneygowhere/logic/commands/ImportCommand.java [hunk 2]
```diff
@@ -125,22 +136,45 @@ public CommandResult execute(Model model) throws CommandException {
         MappingIterator<Map<String, String>> it = mapper.readerFor(Map.class)
                 .with(schema)
                 .readValues(csvFile);
+        JsonParser a = it.getParser();
```
Comment (Nanosync) [inline src/main/java/seedu/moneygowhere/logic/commands/ImportCommand.java]: variable name can be changed

File: src/main/java/seedu/moneygowhere/logic/commands/ImportCommand.java [hunk 3]
```diff
@@ -125,22 +136,45 @@ public CommandResult execute(Model model) throws CommandException {
...
 
+    /**
+     * Returns true if csv has the correct size and headers
+     * @param map A map representing a row of values from the csv file
+     */
+    public boolean isValidCsv(Map<String, String> map) {
+        if (map.size() != 5) {
+            return false;
+        } else {
+            if (map.get("name") == null || map.get("cost") == null || map.get("date") == null
```
Comment (Nanosync) [inline src/main/java/seedu/moneygowhere/logic/commands/ImportCommand.java]: can be refactored

**Review by Nanosync — CHANGES_REQUESTED** [review]

File: src/main/java/seedu/moneygowhere/logic/commands/ImportCommand.java (hunk 3 above)
Comment (jonathantjendana) [reply src/main/java/seedu/moneygowhere/logic/commands/ImportCommand.java]: Done!

File: src/main/java/seedu/moneygowhere/logic/commands/ImportCommand.java (hunk 2 above)
Comment (jonathantjendana) [reply src/main/java/seedu/moneygowhere/logic/commands/ImportCommand.java]: Removed variable

File: src/main/java/seedu/moneygowhere/logic/commands/ImportCommand.java (hunk 1 above)
Comment (jonathantjendana) [reply src/main/java/seedu/moneygowhere/logic/commands/ImportCommand.java]: Done!

File: src/main/java/seedu/moneygowhere/logic/commands/ImportCommand.java [hunk 4]
```diff
@@ -125,22 +135,41 @@ public CommandResult execute(Model model) throws CommandException {
...
 
+    /**
+     * Returns true if csv has the correct size and headers
+     * @param map A map representing a row of values from the csv file
+     */
+    public boolean isValidCsv(Map<String, String> map) {
+        if (map.size() != 5) {
+            return false;
+        } else {
+            String[] keys = "name|cost|date|remark|tagged".split("\\|");
```
Comment (Nanosync) [inline src/main/java/seedu/moneygowhere/logic/commands/ImportCommand.java:168]: This a good approach. You can further improve the approach by moving the String array as a class level constant so that fields can be easily edited when the format changes.

e.g.
```
class ImportCommand {
String[] keys = { FIELD_NAME, FIELD_COST, FIELD_DATE ....`

isValidCsv() {
// simply reference keys here
}
```

**Review by Nanosync — APPROVED** [review]
Good job!
